export const USE_CASE_TOKENS = {
  GET_PORTFOLIO: 'GET_PORTFOLIO_USE_CASE',
  SEARCH_INSTRUMENTS: 'SEARCH_INSTRUMENTS_USE_CASE',
  CREATE_ORDER: 'CREATE_ORDER_USE_CASE',
  CANCEL_ORDER: 'CANCEL_ORDER_USE_CASE',
} as const;
