export const REPOSITORY_TOKENS = {
  USER_REPOSITORY: 'USER_REPOSITORY',
  INSTRUMENT_REPOSITORY: 'INSTRUMENT_REPOSITORY',
  ORDER_REPOSITORY: 'ORDER_REPOSITORY',
  MARKET_DATA_REPOSITORY: 'MARKET_DATA_REPOSITORY',
} as const;
